### PR TITLE
[JENKINS-24380] Stop relying on the format of Run.id

### PR DESCRIPTION
**Pull request by jglick**
To be merged ASAP (cf. https://github.com/jenkinsci/jenkins/pull/1379).

### CODE REVIEW

**Comment by adriankirchner** [comment]
since Jenkins 1.597 this plugin isn't compatible anymore. I think because of the internal changes addressed in this PR.
Please merge and release as soon as possible.

Thanks!

**Comment by daniel-beck** [comment]
[JENKINS-26508](https://issues.jenkins-ci.org/browse/JENKINS-26508)

**Comment by jglick** [comment]
@lvotypko do you expect to merge this?

**Comment by olivergondza** [comment]
Looks good and fixes ATH failures [acceptance-test-harness #690](https://jenkins.ci.cloudbees.com/job/core/job/acceptance-test-harness/690/testReport/).

**Comment by olivergondza** [comment]
@jglick, I was not able to release the plugin, feel free to release it.

> Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.6:deploy (default-deploy) on project disk-usage: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:disk-usage:hpi:0.25 from/to java.net-m2-repository (http://maven.jenkins-ci.org:8081/content/repositories/releases/): Failed to transfer file: http://maven.jenkins-ci.org:8081/content/repositories/releases/org/jenkins-ci/plugins/disk-usage/0.25/disk-usage-0.25.hpi. Return code is: 401, ReasonPhrase: Unauthorized.

**Comment by vjuranek** [comment]
@olivergondza , @jglick , I've released `disk-usage:0.25`

**Comment by jglick** [comment]
Thanks!

**Pull request merged**
